import type { BuiltinLlmProviderTemplate } from "../types";

export const browserBuiltinLlmProviderTemplates: BuiltinLlmProviderTemplate[] = [
	{
		id: "openai",
		displayName: "OpenAI",
		description:
			"官方 API 模板。先登录 OpenAI 平台、创建 API Key，再从常用 Responses / Embedding 模型里选择。",
		registrationLabel: "注册 / 登录",
		registrationUrl: "https://platform.openai.com/signup",
		apiKeyLabel: "API Key 页面",
		apiKeyUrl: "https://platform.openai.com/api-keys",
		docsLabel: "模型与 API 文档",
		docsUrl: "https://platform.openai.com/docs/overview",
		defaultBaseUrl: "https://api.openai.com/v1",
		supportsModelListing: true,
		models: [
			{
				id: "gpt-5.4-mini",
				displayName: "GPT-5.4-mini",
				model: "gpt-5.4-mini",
				modelType: "llm",
				protocol: "responses",
				supportsMultimodal: true,
				supportsStateful: true,
				recommendedFor: ["translation", "rag_answer", "ocr"],
				summary: "通用小型模型，适合翻译、问答和截图理解，默认成本比旗舰档更低。",
				selectableInCurrentApp: true,
				disabledReason: null,
			},
			{
				id: "gpt-5.4",
				displayName: "GPT-5.4",
				model: "gpt-5.4",
				modelType: "llm",
				protocol: "responses",
				supportsMultimodal: true,
				supportsStateful: true,
				recommendedFor: ["translation", "rag_answer", "ocr"],
				summary: "旗舰通用模型，适合高质量翻译、复杂问答和多模态理解。",
				selectableInCurrentApp: true,
				disabledReason: null,
			},
			{
				id: "gpt-5.4-nano",
				displayName: "GPT-5.4-nano",
				model: "gpt-5.4-nano",
				modelType: "llm",
				protocol: "responses",
				supportsMultimodal: true,
				supportsStateful: true,
				recommendedFor: ["translation", "rag_answer", "ocr"],
				summary: "更轻量的通用模型，适合低延迟翻译和基础问答。",
				selectableInCurrentApp: true,
				disabledReason: null,
			},
			{
				id: "text-embedding-3-small",
				displayName: "text-embedding-3-small",
				model: "text-embedding-3-small",
				modelType: "embedding",
				protocol: "responses",
				supportsMultimodal: false,
				supportsStateful: false,
				recommendedFor: ["embedding"],
				summary: "常用 Embedding 模型，适合给 RAG 建立通用文本向量索引。",
				selectableInCurrentApp: true,
				disabledReason: null,
			},
			{
				id: "text-embedding-3-large",
				displayName: "text-embedding-3-large",
				model: "text-embedding-3-large",
				modelType: "embedding",
				protocol: "responses",
				supportsMultimodal: false,
				supportsStateful: false,
				recommendedFor: ["embedding"],
				summary: "更高质量的 Embedding 模型，适合更重视召回质量的 RAG 场景。",
				selectableInCurrentApp: true,
				disabledReason: null,
			},
		],
	},
	{
		id: "openrouter",
		displayName: "OpenRouter",
		description:
			"聚合网关模板。先登录 OpenRouter、创建 API Key，再按当前账号可见的远端模型目录选择模型。",
		registrationLabel: "注册 / 登录",
		registrationUrl: "https://openrouter.ai/",
		apiKeyLabel: "API Key 页面",
		apiKeyUrl: "https://openrouter.ai/settings/keys",
		docsLabel: "官方文档",
		docsUrl: "https://openrouter.ai/docs/quickstart",
		defaultBaseUrl: "https://openrouter.ai/api/v1",
		supportsModelListing: true,
		models: [],
	},
	{
		id: "deepseek",
		displayName: "DeepSeek",
		description:
			"官方 API 模板。先登录 DeepSeek 平台、创建 API Key，再从常用聊天或推理模型里选择。",
		registrationLabel: "注册 / 登录",
		registrationUrl: "https://platform.deepseek.com/",
		apiKeyLabel: "API Key 页面",
		apiKeyUrl: "https://platform.deepseek.com/api_keys",
		docsLabel: "官方文档",
		docsUrl: "https://api-docs.deepseek.com/",
		defaultBaseUrl: "https://api.deepseek.com",
		supportsModelListing: true,
		models: [
			{
				id: "deepseek-chat",
				displayName: "DeepSeek-Chat",
				model: "deepseek-chat",
				modelType: "llm",
				protocol: "chat_completions",
				supportsMultimodal: false,
				supportsStateful: false,
				recommendedFor: ["translation", "rag_answer"],
				summary: "通用对话模型，适合翻译、日常问答和轻量文本生成。",
				selectableInCurrentApp: true,
				disabledReason: null,
			},
			{
				id: "deepseek-reasoner",
				displayName: "DeepSeek-Reasoner",
				model: "deepseek-reasoner",
				modelType: "llm",
				protocol: "chat_completions",
				supportsMultimodal: false,
				supportsStateful: false,
				recommendedFor: ["rag_answer"],
				summary: "推理模型，适合复杂问答、分析和需要多步思考的场景。",
				selectableInCurrentApp: true,
				disabledReason: null,
			},
		],
	},
	{
		id: "ollama",
		displayName: "Ollama",
		description:
			"本地 OpenAI-compatible 模板。先安装 Ollama 并 pull 模型；默认连接本机 `http://localhost:11434/v1`，API Key 可以留空。",
		registrationLabel: "下载 / 安装",
		registrationUrl: "https://ollama.com/download",
		apiKeyLabel: "OpenAI 兼容说明",
		apiKeyUrl: "https://docs.ollama.com/openai",
		docsLabel: "模型与文档",
		docsUrl: "https://docs.ollama.com/",
		defaultBaseUrl: "http://localhost:11434/v1",
		supportsModelListing: true,
		models: [
			{
				id: "qwen3-8b",
				displayName: "Qwen3 8B",
				model: "qwen3:8b",
				modelType: "llm",
				protocol: "responses",
				supportsMultimodal: false,
				supportsStateful: false,
				recommendedFor: ["translation", "rag_answer"],
				summary: "常见本地文本模型，适合日常翻译、问答和低成本试配。",
				selectableInCurrentApp: true,
				disabledReason: null,
			},
			{
				id: "gpt-oss-20b",
				displayName: "gpt-oss 20B",
				model: "gpt-oss:20b",
				modelType: "llm",
				protocol: "chat_completions",
				supportsMultimodal: false,
				supportsStateful: false,
				recommendedFor: ["rag_answer"],
				summary: "常见本地推理模型，适合复杂问答、解释和代码辅助场景。",
				selectableInCurrentApp: true,
				disabledReason: null,
			},
			{
				id: "qwen3-vl-8b",
				displayName: "Qwen3-VL 8B",
				model: "qwen3-vl:8b",
				modelType: "llm",
				protocol: "chat_completions",
				supportsMultimodal: true,
				supportsStateful: false,
				recommendedFor: ["rag_answer"],
				summary: "常见本地图像理解模型，适合截图和文档理解；当前不会进入 OCR 列表。",
				selectableInCurrentApp: true,
				disabledReason: null,
			},
			{
				id: "embeddinggemma",
				displayName: "EmbeddingGemma",
				model: "embeddinggemma",
				modelType: "embedding",
				protocol: "responses",
				supportsMultimodal: false,
				supportsStateful: false,
				recommendedFor: ["embedding"],
				summary: "常见本地 Embedding 模型，适合给 RAG 建立向量索引。",
				selectableInCurrentApp: true,
				disabledReason: null,
			},
		],
	},
	{
		id: "zhipu",
		displayName: "智谱 AI",
		description: "官方免费模型目录模板。先注册智谱开放平台、创建 API Key，再从白名单里选择模型。",
		registrationLabel: "注册 / 登录",
		registrationUrl: "https://bigmodel.cn/login?redirect=%2Fusercenter%2Fproj-mgmt%2Fapikeys",
		apiKeyLabel: "API Key 页面",
		apiKeyUrl: "https://bigmodel.cn/login?redirect=%2Fusercenter%2Fproj-mgmt%2Fapikeys",
		docsLabel: "官方文档",
		docsUrl: "https://docs.bigmodel.cn/cn/guide/start/quick-start",
		defaultBaseUrl: "https://open.bigmodel.cn/api/paas/v4",
		supportsModelListing: true,
		models: [
			{
				id: "glm-4.7-flash",
				displayName: "GLM-4.7-Flash",
				model: "glm-4.7-flash",
				modelType: "llm",
				protocol: "chat_completions",
				supportsMultimodal: false,
				supportsStateful: false,
				recommendedFor: ["translation", "rag_answer"],
				summary: "免费文本模型，适合翻译、问答和通用长文本任务。",
				selectableInCurrentApp: true,
				disabledReason: null,
			},
			{
				id: "glm-4.6v-flash",
				displayName: "GLM-4.6V-Flash",
				model: "glm-4.6v-flash",
				modelType: "llm",
				protocol: "chat_completions",
				supportsMultimodal: true,
				supportsStateful: false,
				recommendedFor: ["translation", "rag_answer"],
				summary: "免费视觉理解模型，擅长图像、视频和文件理解。",
				selectableInCurrentApp: true,
				disabledReason: null,
			},
			{
				id: "glm-4.1v-thinking-flash",
				displayName: "GLM-4.1V-Thinking-Flash",
				model: "glm-4.1v-thinking-flash",
				modelType: "llm",
				protocol: "chat_completions",
				supportsMultimodal: true,
				supportsStateful: false,
				recommendedFor: ["translation", "rag_answer"],
				summary: "免费视觉推理模型，适合图表、GUI 和网页理解场景。",
				selectableInCurrentApp: true,
				disabledReason: null,
			},
			{
				id: "glm-4-flash-250414",
				displayName: "GLM-4-Flash-250414",
				model: "glm-4-flash-250414",
				modelType: "llm",
				protocol: "chat_completions",
				supportsMultimodal: false,
				supportsStateful: false,
				recommendedFor: ["translation", "rag_answer"],
				summary: "免费轻量文本模型，适合通用对话、翻译和基础问答。",
				selectableInCurrentApp: true,
				disabledReason: null,
			},
			{
				id: "glm-4v-flash",
				displayName: "GLM-4V-Flash",
				model: "glm-4v-flash",
				modelType: "llm",
				protocol: "chat_completions",
				supportsMultimodal: true,
				supportsStateful: false,
				recommendedFor: ["translation", "rag_answer"],
				summary: "免费图像理解模型，适合图像识别、问答和视觉推理。",
				selectableInCurrentApp: true,
				disabledReason: null,
			},
			{
				id: "cogview-3-flash",
				displayName: "CogView-3-Flash",
				model: "cogview-3-flash",
				modelType: "image_generation",
				protocol: "unsupported",
				supportsMultimodal: false,
				supportsStateful: false,
				recommendedFor: [],
				summary: "免费图像生成模型，适合根据文本快速生成图片。",
				selectableInCurrentApp: false,
				disabledReason: "当前 Wabity 没有图像生成链路，不能当普通 LLM 使用。",
			},
			{
				id: "cogvideox-flash",
				displayName: "CogVideoX-Flash",
				model: "cogvideox-flash",
				modelType: "video_generation",
				protocol: "unsupported",
				supportsMultimodal: false,
				supportsStateful: false,
				recommendedFor: [],
				summary: "免费视频生成模型，适合根据文本指令生成短视频。",
				selectableInCurrentApp: false,
				disabledReason: "当前 Wabity 没有视频生成链路，不能当普通 LLM 使用。",
			},
		],
	},
	{
		id: "siliconflow",
		displayName: "SiliconFlow",
		description:
			"官方免费语言模型目录模板。先注册 SiliconFlow、创建 API Key，再从白名单里选择模型。",
		registrationLabel: "注册 / 登录",
		registrationUrl: "https://account.siliconflow.cn",
		apiKeyLabel: "API Key 页面",
		apiKeyUrl: "https://cloud.siliconflow.cn/account/ak",
		docsLabel: "官方文档",
		docsUrl: "https://docs.siliconflow.cn/cn/api-reference/chat-completions/chat-completions",
		defaultBaseUrl: "https://api.siliconflow.cn/v1",
		supportsModelListing: true,
		models: [
			{
				id: "qwen3.5-4b-instruct-2507",
				displayName: "Qwen3.5-4B-Instruct-2507",
				model: "Qwen/Qwen3.5-4B-Instruct-2507",
				modelType: "llm",
				protocol: "chat_completions",
				supportsMultimodal: false,
				supportsStateful: false,
				recommendedFor: ["translation", "rag_answer"],
				summary: "免费轻量指令模型，适合低成本翻译、问答和日常文本任务。",
				selectableInCurrentApp: true,
				disabledReason: null,
			},
			{
				id: "paddleocr-vl-1.5",
				displayName: "PaddleOCR-VL-1.5",
				model: "PaddlePaddle/PaddleOCR-VL-1.5",
				modelType: "llm",
				protocol: "chat_completions",
				supportsMultimodal: true,
				supportsStateful: false,
				recommendedFor: ["rag_answer"],
				summary: "免费文档理解模型，适合票据、表格和复杂版面 OCR 识别。",
				selectableInCurrentApp: true,
				disabledReason: null,
			},
			{
				id: "deepseek-r1-distill-qwen-7b",
				displayName: "DeepSeek-R1-Distill-Qwen-7B",
				model: "deepseek-ai/DeepSeek-R1-Distill-Qwen-7B",
				modelType: "llm",
				protocol: "chat_completions",
				supportsMultimodal: false,
				supportsStateful: false,
				recommendedFor: ["translation", "rag_answer"],
				summary: "免费轻量推理模型，适合分析、问答和需要推理的文本任务。",
				selectableInCurrentApp: true,
				disabledReason: null,
			},
			{
				id: "glm-4.1v-9b-thinking",
				displayName: "GLM-4.1V-9B-Thinking",
				model: "THUDM/GLM-4.1V-9B-Thinking",
				modelType: "llm",
				protocol: "chat_completions",
				supportsMultimodal: true,
				supportsStateful: false,
				recommendedFor: ["rag_answer"],
				summary: "免费视觉推理模型，适合图表、截图和复杂图像理解。",
				selectableInCurrentApp: true,
				disabledReason: null,
			},
			{
				id: "paddleocr-vl",
				displayName: "PaddleOCR-VL",
				model: "PaddlePaddle/PaddleOCR-VL",
				modelType: "llm",
				protocol: "chat_completions",
				supportsMultimodal: true,
				supportsStateful: false,
				recommendedFor: ["rag_answer"],
				summary: "免费 OCR / 文档解析模型，适合表格、票据和富版面内容提取。",
				selectableInCurrentApp: true,
				disabledReason: null,
			},
			{
				id: "deepseek-ocr",
				displayName: "DeepSeek-OCR",
				model: "deepseek-ai/DeepSeek-OCR",
				modelType: "llm",
				protocol: "chat_completions",
				supportsMultimodal: true,
				supportsStateful: false,
				recommendedFor: ["rag_answer"],
				summary: "免费 OCR 模型，适合截图、扫描件和文档文字提取。",
				selectableInCurrentApp: true,
				disabledReason: null,
			},
			{
				id: "qwen3-8b",
				displayName: "Qwen3-8B",
				model: "Qwen/Qwen3-8B",
				modelType: "llm",
				protocol: "chat_completions",
				supportsMultimodal: false,
				supportsStateful: false,
				recommendedFor: ["translation", "rag_answer"],
				summary: "免费通用文本模型，适合对话、翻译和基础问答。",
				selectableInCurrentApp: true,
				disabledReason: null,
			},
			{
				id: "hunyuan-mt-7b",
				displayName: "Hunyuan-MT-7B",
				model: "tencent/Hunyuan-MT-7B",
				modelType: "llm",
				protocol: "chat_completions",
				supportsMultimodal: false,
				supportsStateful: false,
				recommendedFor: ["translation"],
				summary: "免费机器翻译模型，适合中英文和多语种翻译场景。",
				selectableInCurrentApp: true,
				disabledReason: null,
			},
			{
				id: "deepseek-r1-0528-qwen3-8b",
				displayName: "DeepSeek-R1-0528-Qwen3-8B",
				model: "deepseek-ai/DeepSeek-R1-0528-Qwen3-8B",
				modelType: "llm",
				protocol: "chat_completions",
				supportsMultimodal: false,
				supportsStateful: false,
				recommendedFor: ["rag_answer"],
				summary: "免费推理模型，适合复杂问答和需要多步分析的任务。",
				selectableInCurrentApp: true,
				disabledReason: null,
			},
			{
				id: "glm-z1-9b-0414",
				displayName: "GLM-Z1-9B-0414",
				model: "THUDM/GLM-Z1-9B-0414",
				modelType: "llm",
				protocol: "chat_completions",
				supportsMultimodal: false,
				supportsStateful: false,
				recommendedFor: ["rag_answer"],
				summary: "免费推理模型，适合代码解释、复杂问答和长链思考。",
				selectableInCurrentApp: true,
				disabledReason: null,
			},
			{
				id: "qwen2.5-7b-instruct",
				displayName: "Qwen2.5-7B-Instruct",
				model: "Qwen/Qwen2.5-7B-Instruct",
				modelType: "llm",
				protocol: "chat_completions",
				supportsMultimodal: false,
				supportsStateful: false,
				recommendedFor: ["translation", "rag_answer"],
				summary: "免费通用指令模型，适合日常问答、改写和轻量生成。",
				selectableInCurrentApp: true,
				disabledReason: null,
			},
			{
				id: "glm-4-9b-0414",
				displayName: "GLM-4-9B-0414",
				model: "THUDM/GLM-4-9B-0414",
				modelType: "llm",
				protocol: "chat_completions",
				supportsMultimodal: false,
				supportsStateful: false,
				recommendedFor: ["translation", "rag_answer"],
				summary: "免费通用文本模型，适合对话、翻译和基础知识问答。",
				selectableInCurrentApp: true,
				disabledReason: null,
			},
			{
				id: "internlm2-5-7b-chat",
				displayName: "internlm2_5-7b-chat",
				model: "internlm/internlm2_5-7b-chat",
				modelType: "llm",
				protocol: "chat_completions",
				supportsMultimodal: false,
				supportsStateful: false,
				recommendedFor: ["translation", "rag_answer"],
				summary: "免费聊天模型，适合日常问答和轻量文本生成。",
				selectableInCurrentApp: true,
				disabledReason: null,
			},
		],
	},
];
